import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ObjectHash {
    public String hexDigest(String value) throws NoSuchAlgorithmException {
        MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
        sha256.update("u".getBytes());

        // TODO: this needs to UTF8 encode and do unicode normalisation

        sha256.update(value.getBytes());
        StringBuilder sb = new StringBuilder();
        for (byte b : sha256.digest()) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }
}
