/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.security.NoSuchAlgorithmException;

public class ObjectHashTest {
    @Test public void testStringHexDigest() throws NoSuchAlgorithmException {
        ObjectHash classUnderTest = new ObjectHash();
        assertEquals(classUnderTest.hexDigest("Hello, Ruby!"), "c92765c1350e6df6800dbadedb3420f398d5f3c7e38a3da48aadb3332280f85f");
    }
}
